const projectInfo = [{ projectTitle: "Landing Page1", subTitle: "A minimal hero section with smooth scroll CTA.", imgPath: "/src/assets/projects photo/landing-page1.jpg", link: "https://alialhamawy.github.io/html_css_project1/", gitRepo: "https://github.com/AliALHamawy/html_css_project1", note: "The site build with HTML and CSS" },
{ projectTitle: "Landing Page2", subTitle: "Modern product layout built with pure CSS grids.", imgPath: "/src/assets/projects photo/Landing%20Page2.jpg", link: "https://alialhamawy.github.io/html_css_project2/#include", gitRepo: "https://github.com/AliALHamawy/html_css_project2", note: "The site build with HTML and CSS" },
{ projectTitle: "Landing Page3", subTitle: "Lifestyle landing with storytelling copy and imagery.", imgPath: "/src/assets/projects photo/Landing%20Page3.jpg", link: "https://alialhamawy.github.io/Html_Css_Project3/", gitRepo: "https://github.com/AliALHamawy/Html_Css_Project3", note: "The site build with HTML and CSS" },
{ projectTitle: "Landing Page4", subTitle: "Interactive landing that adds micro‑animations via JS.", imgPath: "/src/assets/projects photo/JS Landing Page.jpg", link: "https://alialhamawy.github.io/Project5/", gitRepo: "https://github.com/AliALHamawy/Project5", note: "The site build with HTML, CSS and JS" },
{ projectTitle: "BootStrap", subTitle: "Responsive multi-section site powered by Bootstrap 5.", imgPath: "/src/assets/projects photo/BootStrap.jpg", link: "https://alialhamawy.github.io/First-BootStrap/", gitRepo: "https://github.com/AliALHamawy/First-BootStrap", note: "The site build with HTML, CSS, JS and BootStrab" },
{ projectTitle: "Account ", subTitle: "Clean account dashboard concept with cards and stats.", imgPath: "/src/assets/projects photo/Account%20.jpg", link: "https://alialhamawy.github.io/Acounts/", gitRepo: "https://github.com/AliALHamawy/Acounts", note: "The site build with HTML and CSS" },
{ projectTitle: "Login Form", subTitle: "Glassmorphism login experience with subtle hover states.", imgPath: "/src/assets/projects photo/Login%20Form.jpg", link: "http://alialhamawy.github.io/Login-repo/index.html", gitRepo: "https://github.com/AliALHamawy/Login-repo", note: "The site build with HTML and CSS" },
{ projectTitle: "Product", subTitle: "Premium product card showcasing price, rating, and CTA.", imgPath: "/src/assets/projects photo/product.png", link: "https://alialhamawy.github.io/Prodcut-Card/", gitRepo: "https://github.com/AliALHamawy/Prodcut-Card", note: "The site build with HTML and CSS, Dosen't support small screens" },
{ projectTitle: "TailwindCss Loading Page", subTitle: "Premium loading page built with Tailwind CSS.", imgPath: "/src/assets/projects photo/TailwindCss Loading Page.png", link: "https://alialhamawy.github.io/First-Tailwind/", gitRepo: "https://github.com/AliALHamawy/First-Tailwind/", note: "The site build with HTML and TailwindCss" },
{ projectTitle: "Calculator", subTitle: "A lightweight JS calculator with keyboard shortcuts.", imgPath: "/src/assets/projects photo/Calc.jpg", link: "https://alialhamawy.github.io/calculator/", gitRepo: "https://github.com/AliALHamawy/calculator", note: "The site build with HTML, CSS and JS" },
{ projectTitle: "ToDo List", subTitle: "React todo app with filtering, persistence, and stats.", imgPath: "/src/assets/projects photo/ToDo%20List.jpg", link: "https://to-o-list.netlify.app/", gitRepo: "https://github.com/AliALHamawy/ToDo-List", note: "The site build React" },
{ projectTitle: "X - O Game", subTitle: "Tic‑Tac‑Toe built in React with smart win detection.", imgPath: "/src/assets/projects photo/X-O%20game.jpg", link: "https://alialhamawy.github.io/x-o-game//", gitRepo: "https://github.com/AliALHamawy/X-O-game", note: "The site build with React" },
{ projectTitle: "Old Portfolio", subTitle: "An old portfolio website.", imgPath: "/src/assets/projects photo/Old Portfolio.png", link: "https://alialhamawy.github.io/portfolio/", gitRepo: "https://github.com/AliALHamawy/portfolio/", note: "The site build with React" },
{ projectTitle: "New Accounts", subTitle: "A new accounts website with some new features.", imgPath: "/src/assets/projects photo/new accounts.png", link: "https://new-account.pages.dev/", gitRepo: "https://github.com/AliALHamawy/new-account-", note: "The site build with React" }
];

export default projectInfo
