export const myProjects = [
    { projectTitle: "Landing Page1", subTitle: "A minimal hero section with smooth scroll CTA.", category: "css", imgPath: "/src/assets/projects photo/landing-page1.jpg", link: "https://alialhamawy.github.io/html_css_project1/", gitRepo: "https://github.com/AliALHamawy/html_css_project1" },
    { projectTitle: "Landing Page2", subTitle: "Modern product layout built with pure CSS grids.", category: "css", imgPath: "/src/assets/projects photo/Landing%20Page2.jpg", link: "https://alialhamawy.github.io/html_css_project2/#include", gitRepo: "https://github.com/AliALHamawy/html_css_project2" },
    { projectTitle: "Landing Page3", subTitle: "Lifestyle landing with storytelling copy and imagery.", category: "css", imgPath: "/src/assets/projects photo/Landing%20Page3.jpg", link: "https://alialhamawy.github.io/Html_Css_Project3/", gitRepo: "https://github.com/AliALHamawy/Html_Css_Project3" },
    { projectTitle: "Landing Page4", subTitle: "Interactive landing that adds micro‑animations via JS.", category: "js", imgPath: "/src/assets/projects photo/JS Landing Page.jpg", link: "https://alialhamawy.github.io/Project5/", gitRepo: "https://github.com/AliALHamawy/Project5" },
    { projectTitle: "BootStrap", subTitle: "Responsive multi-section site powered by Bootstrap 5.", category: "bootstrap", imgPath: "/src/assets/projects photo/BootStrap.jpg", link: "https://alialhamawy.github.io/First-BootStrap/", gitRepo: "https://github.com/AliALHamawy/First-BootStrap" },
    { projectTitle: "Account ", subTitle: "Clean account dashboard concept with cards and stats.", category: "css", imgPath: "/src/assets/projects photo/Account%20.jpg", link: "https://alialhamawy.github.io/Acounts/", gitRepo: "https://github.com/AliALHamawy/Acounts" },
    { projectTitle: "Login Form", subTitle: "Glassmorphism login experience with subtle hover states.", category: "css", imgPath: "/src/assets/projects photo/Login%20Form.jpg", link: "http://alialhamawy.github.io/Login-repo/index.html", gitRepo: "https://github.com/AliALHamawy/Login-repo" },
    { projectTitle: "Calculator", subTitle: "A lightweight JS calculator with keyboard shortcuts.", category: "js", imgPath: "/src/assets/projects photo/Calc.jpg", link: "https://alialhamawy.github.io/calculator/", gitRepo: "https://github.com/AliALHamawy/calculator" },
    { projectTitle: "ToDo List", subTitle: "React todo app with filtering, persistence, and stats.", category: "react", imgPath: "/src/assets/projects photo/ToDo%20List.jpg", link: "https://to-o-list.netlify.app/", gitRepo: "https://github.com/AliALHamawy/ToDo-List" },
    { projectTitle: "X - O Game", subTitle: "Tic‑Tac‑Toe built in React with smart win detection.", category: "react", imgPath: "/src/assets/projects photo/X-O%20game.jpg", link: "https://alialhamawy.github.io/x-o-game//", gitRepo: "https://github.com/AliALHamawy/X-O-game" },
    { projectTitle: "Product", subTitle: "Premium product card showcasing price, rating, and CTA.", category: "css", imgPath: "/src/assets/projects photo/product.png", link: "https://alialhamawy.github.io/Prodcut-Card/", gitRepo: "https://github.com/AliALHamawy/Prodcut-Card" },
    { projectTitle: "TailwindCss Loading Page", subTitle: "Premium loading page built with Tailwind CSS.", category: "tailwind", imgPath: "/src/assets/projects photo/TailwindCss Loading Page.png", link: "https://alialhamawy.github.io/First-Tailwind/", gitRepo: "https://github.com/AliALHamawy/First-Tailwind/" },
    { projectTitle: "Old Portfolio", subTitle: "An old portfolio website.", category: "React", imgPath: "/src/assets/projects photo/Old Portfolio.png", link: "https://alialhamawy.github.io/portfolio/", gitRepo: "https://github.com/AliALHamawy/portfolio/" },
    { projectTitle: "New Accounts", subTitle: "A new accounts website with some new features.", category: "React", imgPath: "/src/assets/projects photo/new accounts.png", link: "https://new-account.pages.dev/", gitRepo: "https://github.com/AliALHamawy/new-account-" }
];